version: '3.8'

services:
  api:
    build: .
    command: sh ./init.sh
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:-admin}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin}
    volumes:
      - .:/app
    #depends_on:
    #  - db

  #db:
  #  image: postgres:13
  #  environment:
  #    POSTGRES_DB: your_db_name
  #    POSTGRES_USER: your_db_user
  #    POSTGRES_PASSWORD: your_db_password
  #  ports:
  #    - "5432:5432"
