version: '3.8'

services:
  linkhub:
    build:
      context: . 
    container_name: linkhub
    environment:
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "chmod +x /app/init.sh && /app/init.sh"]

  db:
    image: postgres:15
    container_name: linkhub-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
