# Generated by Django 5.1.2 on 2024-10-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='user_id',
        ),
    ]
