# Generated by Django 5.1.2 on 2024-10-22 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('link_app', '0001_initial'),
        ('room_app', '0002_rename_user_room_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=1024)),
                ('links', models.ManyToManyField(blank=True, to='link_app.link')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_app.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
